import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { RelayEnvironmentProvider } from "react-relay";
import environment from "@/relay/environment";
import RelayClientProvider from "@/components/relay-client-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RelayClientProvider>
          <ThemeProvider defaultTheme="dark">
            <main className="mx-auto container my-4">{children}</main>
          </ThemeProvider>
        </RelayClientProvider>
      </body>
    </html>
  );
}
